import Head from 'next/head';
import Feature from '../components/Features/Feature';
import Header from '../components/Header';
import Hero from '../components/Hero/Hero';
import Property from '../components/Property/Property';
import Testimonial from '../components/Testimonial/Testimonial';

export default function Home() {
  return (
    <div className='font-mont'>
      <Head>
        <title>The Future Group</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='max-w-7xl mx-auto'>
          <Header />
        </div>
        <div className='main-hero-bg '>
          <div className='max-w-7xl mx-auto'>
            <Hero />
          </div>
        </div>
        <div className='max-w-7xl mx-auto'>
          <Property />
        </div>
        <div className='max-w-7xl mx-auto'>
          <Feature />
        </div>
        <div className='max-w-7xl mx-auto py-10'>
          <Testimonial />
        </div>
      </main>
    </div>
  );
}
