/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import Dail from '../components/dailouge/Dail';
import Feature from '../components/Features/Feature';
import Header from '../components/Header';
import Hero from '../components/Hero/Hero';
import Property from '../components/Property/Property';
import Testimonial from '../components/Testimonial/Testimonial';

export default function Home() {
  const [banner, setBanner] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => {
      setBanner(true);
    }, 3000);

    return () => {
      return t;
    };
  }, []);

  return (
    <div className='font-mont'>
      <Head>
        <title>The Future Group</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {banner ? <Dail b={banner} setB={setBanner} /> : ''}
      <main>
        <div className='main-hero-bg  relative'>
          <div className='max-w-7xl mx-auto'>
            <Hero />
          </div>
        </div>
        <div className='max-w-7xl mx-auto'>
          <Property />
        </div>
        <div className='max-w-7xl mx-auto'>
          <Feature />
        </div>
        <div className='max-w-7xl mx-auto py-10'>
          <Testimonial />
        </div>
      </main>
    </div>
  );
}
